plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nigar.gold.savings'
    compileSdk 35

    defaultConfig {
        applicationId 'com.nigar.gold.savings'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }

        release {
            minifyEnabled false
        }
    }
}

dependencies {
}
